<a href="https://colab.research.google.com/github/SofiaKakou/Customer_Churn_Prediction/blob/main/notebooks/08_bank_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Introduction

This notebook prepares the bank churn dataset for further analysis and modelling

# 2.Imports

In [1]:
# importing packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder

import warnings
warnings.filterwarnings("ignore")

# 3.Load Dataset

In [2]:
# mounting to drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Thesis/Datasets/Bank Customer Churn Prediction.csv")

# 4.Basic Cleanup

In [4]:
# checking for missing values
df.isna().sum()

customer_id         0
credit_score        0
country             0
gender              0
age                 0
tenure              0
balance             0
products_number     0
credit_card         0
active_member       0
estimated_salary    0
churn               0
dtype: int64

In [5]:
# checking for duplicates
df.duplicated().sum()

np.int64(0)

In [7]:
# encoding categorical features

df_encoded = pd.get_dummies(
    df,
    columns=["country", "gender"],
    drop_first=True
)

df_encoded.head()

,customer_id,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,country_Germany,country_Spain,gender_Male
0,15634602,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,15647311,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,15619304,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,15701354,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,15737888,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

# 5.Save Clean Dataset

In [8]:
save_path="/content/drive/MyDrive/Thesis/Datasets/bank_cleaned.csv"
df_encoded.to_csv(save_path, index=False)