<a href="https://colab.research.google.com/github/SofiaKakou/Customer_Churn_Prediction/blob/main/notebooks/10_bank_feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Introduction

This notebook prepares the cleaned Bank Churn dataset for ML practices.
*   review the cleaned dataset
*   remove irrelevant columns
*   confirm target variable
*    select final features
*   define x and y
*    split data into training/ testing sets
*   saved the prepared datasets for modelling

# 2.Imports

In [1]:
# importing packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings("ignore")

# 3.Load Dataset

In [2]:
# Mount Google Drive
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Load Clean Dataset
path = "/content/drive/MyDrive/Thesis/Datasets/bank_cleaned.csv"

df = pd.read_csv(path)

df.head()

,customer_id,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn,country_Germany,country_Spain,gender_Male
0,15634602,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,15647311,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,15619304,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,15701354,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,15737888,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

# 4.Confirm Target Variable
The target variable is "Churn", which indicates wether a customer left the service.

- 1 = customer churned
- 0 = customer did not churn

In [4]:
# target distribution
df["churn"].value_counts()

churn
0    7963
1    2037
Name: count, dtype: int64

In [5]:
# % target distribution
df["churn"].value_counts(normalize=True)*100

churn
0    79.63
1    20.37
Name: proportion, dtype: float64

# 5.Remove Irrelevant Columns

In [6]:
df.columns.tolist()

['customer_id',
 'credit_score',
 'age',
 'tenure',
 'balance',
 'products_number',
 'credit_card',
 'active_member',
 'estimated_salary',
 'churn',
 'country_Germany',
 'country_Spain',
 'gender_Male']

In [7]:
# irrelevant id column
cols_to_drop = ['customer_id']

In [8]:
df = df.drop(columns=cols_to_drop)

print("Remaining Columns:", df.columns.tolist())

Remaining Columns: ['credit_score', 'age', 'tenure', 'balance', 'products_number', 'credit_card', 'active_member', 'estimated_salary', 'churn', 'country_Germany', 'country_Spain', 'gender_Male']

## Observations

The following columns were removed:
- customer_id

This feature was removed because it does not contribute meaningful predictive value.

# 6.Review Outliers

In [9]:
df.describe()

,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,churn
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

## Observations

The dataset shows the presence of outliers in features such as age and credit score, while balance exhibits high variability with a significant proportion of zero values. Most other features display stable distributions without extreme values.

# 7.Feature Selection
The final feature set is selected by separating the input variables from the target ones.
- x contains the input features used to make predictions
- y contains the churn target variable

In [11]:
# define features and target
x = df.drop("churn", axis=1)
y = df["churn"]

print("X shape:", x.shape)
print("y shape:", y.shape)

X shape: (10000, 11)
y shape: (10000,)

In [12]:
x.head()

,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,country_Germany,country_Spain,gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False

In [13]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: churn, dtype: int64

# 8.Train-Test Split
The dataset is split into training and testing sets.

- 80% of the data is used for training the ML
- 20% of the data is used for testing

A fixed random_state is used to make the split reproducible.

In [14]:
# Creating the Split
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
    )

print("X Train Shape:", x_train.shape)
print("y Train Shape:", y_train.shape)
print("X Test Shape:", x_test.shape)
print("y Test Shape:", y_test.shape)

X Train Shape: (8000, 11)
y Train Shape: (8000,)
X Test Shape: (2000, 11)
y Test Shape: (2000,)

In [15]:
print("Training target distribution:")
print(y_train.value_counts(normalize=True)*100)

print("\nTesting target distribution:")
print(y_test.value_counts(normalize=True)*100)

Training target distribution:
churn
0    79.625
1    20.375
Name: proportion, dtype: float64

Testing target distribution:
churn
0    79.65
1    20.35
Name: proportion, dtype: float64

# Observations
The target variable is moderately imbalanced with approximately 80% non churn and 20% churn cases. The consistent distribution across training and testing sets ensues a reliable model evaluation, although appropriate metrics must be use to account for class imbalance.

# 9.Scale Numerical Features

The scaling happens so that features with larger numeric ranges do not dominate models such as Logistic Regression.

Scaling is applied after the train/ test split to avoid leakage.

The scaler is fitted only on the training data, then applied to both training and testing data.

In [16]:
# identifying numerical cols
num_cols = x_train.select_dtypes(include=["int64", "float64"]).columns.tolist()

num_cols

['credit_score',
 'age',
 'tenure',
 'balance',
 'products_number',
 'credit_card',
 'active_member',
 'estimated_salary']

In [17]:
# scale numerical features
scaler = StandardScaler()

x_train_scaled = x_train.copy()
x_test_scaled = x_test.copy()

x_train_scaled[num_cols] = scaler.fit_transform(x_train[num_cols])
x_test_scaled[num_cols] = scaler.transform(x_test[num_cols])

In [18]:
# scaled training data preview
x_train_scaled.head()

,credit_score,age,tenure,balance,products_number,credit_card,active_member,estimated_salary,country_Germany,country_Spain,gender_Male
2151,1.058568,1.715086,0.684723,-1.226059,-0.910256,0.641042,-1.030206,1.042084,False,False,True
8392,0.913626,-0.659935,-0.696202,0.413288,-0.910256,0.641042,-1.030206,-0.623556,True,False,True
5006,1.079274,-0.184931,-1.731895,0.601687,0.808830,0.641042,0.970680,0.308128,True,False,False
4117,-0.929207,-0.184931,-0.005739,-1.226059,0.808830,0.641042,-1.030206,-0.290199,False,False,True
7182,0.427035,0.955079,0.339492,0.548318,0.808830,-1.559960,0.970680,0.135042,True,False,True

# 10.Save Prepared Data

In [19]:
save_folder = "/content/drive/MyDrive/Thesis/Prepared Data/"

x_train_scaled.to_csv(save_folder + "bank_x_train.csv", index=False)
x_test_scaled.to_csv(save_folder + "bank_x_test.csv", index=False)
y_train.to_csv(save_folder + "bank_y_train.csv", index=False)
y_test.to_csv(save_folder + "bank_y_test.csv", index=False)